FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# We only need streamlit and basic requests for frontend
RUN pip install streamlit requests python-dotenv

COPY frontend ./frontend

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
